[package]
name = "aion-state"
version = "0.1.0"
edition = "2024"

[dependencies]
parking_lot = "0.12.5"
tracing = "0.1.44"
thiserror = "2.0.18"

stable_deref_trait = "1.2.1"

[dev-dependencies]
rand = { version = "0.10.1", optional = true }
strum = "0.28.0"
strum_macros = "0.28.0"
rand_chacha = "0.10.0"
lazy_static = "1.5.0"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }

[features]
default = ["default-implementation"]
# default = []
default-implementation = ["rand"]
