#![allow(clippy::type_complexity)]
#![allow(clippy::match_like_matches_macro)]
#![allow(clippy::mut_from_ref)]
#![allow(clippy::single_match)]
#![allow(clippy::len_without_is_empty)]

pub mod synchronised_registry;
pub mod accessor;

pub mod prelude {
    pub(crate) const FUNCTION_LEVEL: tracing::Level = tracing::Level::DEBUG;

    pub(crate) mod sync {
        #[allow(unused_imports)]
        pub use parking_lot::Mutex;
        pub use parking_lot::RwLock;
        #[allow(clippy::disallowed_types)]
        pub use std::sync::Arc;
    }

    macro_rules! trace_function {
        ($log:literal) => {
            let span = tracing::span!(crate::prelude::FUNCTION_LEVEL, $log);
            let _enter = span.enter();
        };
    }

    pub(crate) use trace_function;

    pub use super::synchronised_registry::SynchronisedRegistry;
    pub use super::synchronised_registry::registry::UnsynchronisedRegistry as UnsynchronisedRegistry;
    
    #[cfg(not(feature = "sync"))]
    pub use super::synchronised_registry::registry::UnsynchronisedRegistry as Registry;
    
    #[cfg(feature = "sync")]
    pub use super::synchronised_registry::SynchronisedRegistry as Registry;

    pub use super::{
        synchronised_registry::{
            releaser::{
                Releaser,
                releasing_result::{
                    ReleasingResult,
                }
            },
            registry_results::{
                RegistryRegisterResult,
                RegistryAcquireAccessError,
                RegistryBlacklistAllowResult,
                RegistryBlacklistUnallowResult,
                RegistryCheckAccessResult,
                RegistryContainsResourceResult,
                RegistryDrainReservationsResult,
                RegistryOwnResult,
                RegistryReleaseAccessResult,
                RegistryReleaseResourceAllResult,
                RegistryReleaseResourceResult,
                RegistryReservationResult,
                RegistrySaferReplacementResult,
                RegistryUnregisterResult,
                RegistryUnreserveResult,
                RegistryUpdatePasswordResult,
                RegistryWhitelistAllowResult,
                RegistryWhitelistUnallowResult,
            },
            registry::{
                registry_input::{
                    RegistryRegister,
                    RegistryUnregister,
                    RegistryUpdatePassword,
                    RegistryOwn,
                    RegistryReleaseResource,
                    RegistryReleaseResourceAll,
                    RegistryAllow,
                    RegistryUnallow,
                    RegistryCheckAccess,
                    RegistryReleaseAccess,
                    RegistryReleasingReleaseAccess,
                    RegistryReservation,
                    RegistryUnreserve,
                    RegistryDrainReservations,
                    RegistryAcquireAccess,
                    RegistryReleasingAcquireAccess,
                    RegistrySaferReplacement,
                    RegistryContainsResource,
                },
                unsynchronised_registry_result::{
                    UnsynchronisedRegistryRegisterResult,
                    UnsynchronisedRegistryUnregisterResult,
                    UnsynchronisedRegistryUpdatePasswordResult,
                    UnsynchronisedRegistryOwnResult,
                    UnsynchronisedRegistryReleaseResourceResult,
                    UnsynchronisedRegistryReleaseResourceAllResult,
                    UnsynchronisedRegistryBlacklistAllowResult,
                    UnsynchronisedRegistryWhitelistAllowResult,
                    UnsynchronisedRegistryBlacklistUnallowResult,
                    UnsynchronisedRegistryWhitelistUnallowResult,
                    UnsynchronisedRegistryCheckAccessResult,
                    UnsynchronisedRegistryReleaseAccessResult,
                    UnsynchronisedRegistryReservationResult,
                    UnsynchronisedRegistryUnreserveResult,
                    UnsynchronisedRegistryDrainReservationsResult,
                    UnsynchronisedRegistryAcquireAccessError,
                    UnsynchronisedRegistrySaferReplacementResult,
                    UnsynchronisedRegistryContainsResourceResult,
                },
                coordinated_reception::{
                    CoordinatedReception,
                    reception::{
                        Reception,
                        reception_input::{
                            ReceptionRegister,
                            ReceptionUnregister,
                            ReceptionUpdatePassword,
                            ReceptionOwn,
                            ReceptionReleaseResource,
                            ReceptionAllow,
                            ReceptionUnallow,
                            ReceptionReleaseResourceAll,
                            ReceptionCheckAccess,
                            ReceptionReleaseAccess,
                            ReceptionRecordAccess,
                            ReceptionReservation,
                            ReceptionUnreserve,
                            ReceptionDrainReservations,
                            ReceptionGetAccess
                        },
                        reception_result::{
                            ReceptionRegisterResult,
                            ReceptionUnregisterResult,
                            ReceptionUpdatePasswordResult,
                            ReceptionOwnResult,
                            ReceptionReleaseResourceResult,
                            ReceptionWhitelistAllowResult,
                            ReceptionBlacklistAllowResult,
                            ReceptionWhitelistUnallowResult,
                            ReceptionBlacklistUnallowResult,
                            ReceptionReleaseResourceAllResult,
                            ReceptionCheckAccessResult,
                            ReceptionReleaseAccessResult,
                            ReceptionRecordAccessResult,
                            ReceptionReservationResult,
                            ReceptionUnreserveResult,
                            ReceptionDrainReservationsResult
                        },
                        host::{
                            Host,
                            host_input::{
                                HostCheckAccess,
                                HostRecordAccess,
                                HostReleaseAccess,
                                HostReservation,
                                HostUnreserve,
                                HostDrainReservations,
                                HostGetAccess,
                            },
                            host_result::{
                                HostCheckAccessResult,
                                HostRecordAccessResult,
                                HostReservationResult,
                                HostUnreserveResult,
                                HostReleaseAccessResult,
                                HostDrainReservationsResult,
                            },
                            reservations::{
                                Reservations,
                                reservation_storage::{
                                    ReservationStorage
                                },
                                reservations_input::{
                                    ReservationsCheckAccess, 
                                    ReservationsReservation,
                                    ReservationsUnreserve,
                                    ReservationsDrainReservations,
                                },
                                reservations_result::{
                                    ReservationsCheckAccessResult,
                                    ReservationsReserveResult,
                                    ReservationsUnreserveResult,
                                    ReservationsDrainReservationsResult
                                },
                            },
                            accesses::{
                                Accesses,
                                access_storage::{
                                    AccessStorage
                                },
                                accesses_result::{
                                    AccessesCheckAccessResult,
                                    AccessesRecordAccessResult,
                                    AccessesReleaseResult,
                                    AccessesDrainResult
                                },
                                accesses_input::{
                                    AccessesCheckAccess, 
                                    AccessesRecordAccess,
                                    AccessesRelease,
                                    GetAccess,
                                }
                            }
                        },
                        owner::{
                            Owner,
                            owner_input::{
                                OwnerOwn,
                                OwnerRegister,
                                OwnerReleaseResource,
                                OwnerUpdatePassword,
                                OwnerUnregister,
                                OwnerAllow,
                                OwnerCheckAccess,
                                OwnerUnallow,
                                OwnerReleaseResourceAll,
                                OwnerAuthenticate
                            },
                            owner_result::{
                                OwnerOwnResult,
                                OwnerRegisterResult,
                                OwnerReleaseResourceResult,
                                OwnerUpdatePasswordResult,
                                OwnerUnregisterResult,
                                OwnerBlacklistAllowResult,
                                OwnerWhitelistAllowResult,
                                OwnerCheckAccessResult,
                                OwnerWhitelistUnallowResult,
                                OwnerBlacklistUnallowResult,
                                OwnerReleaseResourceAllResult,
                                OwnerAuthenticationResult
                            },
                            authenticator::{
                                Authenticator,
                                authenticator_input::{
                                    Authentication,
                                    AuthenticateRegister,
                                    AuthenticateUpdatePassword,
                                    AuthenticateUnregister
                                },
                                authenticator_result::{
                                    AuthenticationResult,
                                    AuthenticateRegistrationResult,
                                    AuthenticateUpdatePasswordResult,
                                    AuthenticateUnregisterResult
                                },
                                credential_storage::{
                                    CredentialStorage
                                },
                            },
                            controller::{
                                Controller,
                                controller_input::{
                                    ControllerOwn,
                                    ControllerReleaseResource,
                                    ControllerAllow,
                                    ControllerCheckAccess,
                                    ControllerReleaseId,
                                    ControllerCheckOwner,
                                    ControllerUnallow,
                                },
                                controller_result::{
                                    ControllerOwnResult,
                                    ControllerReleaseResourceResult,
                                    ControllerBlacklistAllowResult,
                                    ControllerWhitelistAllowResult,
                                    ControllerCheckAccessResult,
                                    ControllerReleaseIdResult,
                                    ControllerCheckOwnerResult,
                                    ControllerBlacklistUnallowResult,
                                    ControllerWhitelistUnallowResult,
                                    ControllerReleaseResourceAllResult
                                },
                                access_control::{
                                    AccessControl,
                                    access_control_input::{
                                        AccessControlCheckAccess,
                                        AccessControlAllow,
                                        AccessControlRelease,
                                        AccessControlUnallow
                                    },
                                    access_control_result::{
                                        AccessControlCheckAccessResult,
                                        AccessControlBlacklistAllowResult,
                                        AccessControlWhitelistAllowResult,
                                        AccessControlReleaseResult,
                                        AccessControlBlacklistUnallowResult,
                                        AccessControlWhitelistUnallowResult,
                                        AccessControlReleaseAllResult,
                                    },
                                    blacklist::{
                                        Blacklist,
                                        blacklist_input::{
                                            BlacklistCheckAccess,
                                            BlacklistAllow,
                                            BlacklistRelease,
                                            BlacklistUnallow
                                        },
                                        blacklist_result::{
                                            BlacklistCheckAccessResult,
                                            BlacklistAllowResult,
                                            BlacklistReleaseResult,
                                            BlacklistUnallowResult,
                                            BlacklistReleaseAllResult
                                        },
                                        blacklist_storage::{
                                            BlacklistStorage
                                        }
                                    },
                                    whitelist::{
                                        Whitelist,
                                        whitelist_input::{
                                            WhitelistCheckAccess,
                                            WhitelistAllow,
                                            WhitelistRelease,
                                            WhitelistUnallow
                                        },
                                        whitelist_result::{
                                            WhitelistCheckAccessResult,
                                            WhitelistAllowResult,
                                            WhitelistReleaseResult,
                                            WhitelistUnallowResult,
                                            WhitelistReleaseAllResult
                                        },
                                        whitelist_storage::{
                                            WhitelistStorage
                                        }
                                    }
                                },
                                resource_control::{
                                    ResourceControl,
                                    control_storage::{
                                        ControlStorage
                                    },
                                    resource_control_input::{
                                        ResourceControlCheckOwner,
                                        ResourceControlRelease,
                                        ResourceControlOwn,
                                        ResourceControlReleaseId,
                                        ResourceIsOwned,
                                    },
                                    resource_control_result::{
                                        ResourceControlCheckOwnerResult,
                                        ResourceControlReleaseResult,
                                        ResourceControlOwnResult,
                                        ResourceControlReleaseIdResult,
                                        ResourceControlCheckOwnersResult,
                                        ResourceControlIsOwnedResult,
                                    }
                                }
                            }
                        }
                    }
                },
                automated_registry::{
                    AutomatedRegistry,
                    manual_registry::{
                        ManualRegistry,
                        manual_registry_input::{
                            ManualRegistryAccessInput, 
                            ManualRegistryReplacementInput,
                        },
                        manual_registry_result::{
                            ManualRegistryAccessError, 
                            ManualRegistryReplacementResult,
                        },
                        registry_storage::{
                            RegistryStorage
                        },
                    }
                }
            }
        },
        accessor::{
            Accessor,
            AccessorResult,
            StoredValueTrait
        }
    };
}