pub mod registry;
pub mod accessor;

#[cfg(feature = "default-implementation")]
pub mod default;

pub mod prelude {
    pub const FUNCTION_LEVEL: tracing::Level = tracing::Level::DEBUG;

    #[cfg(not(all(test, feature = "loom")))]
    pub(crate) use std::sync;

    #[cfg(all(test, feature = "loom"))]
    pub(crate) use loom::sync;

    // #[cfg(feature = "tokio")]
    // pub(crate) use tokio::sync;

    macro_rules! trace_function {
        ($log:literal) => {
            let span = tracing::span!(crate::prelude::FUNCTION_LEVEL, $log);
            let _enter = span.enter();
        };
    }

    pub(crate) use trace_function;

    pub use super::{
        registry::{
            Registry,
            singular_registry::{
                SingularRegistry,
                singular_registry_input::{
                    SingularRegistryAccessInput
                },
                singular_registry_result::{
                    SingularRegistryAccessResult
                },
                coordinated_reception::{
                    CoordinatedReception,
                    reception::{
                        Reception,
                        reception_input::{
                            ReceptionRegister,
                            ReceptionUnregister,
                            ReceptionUpdatePassword,
                            ReceptionOwn,
                            ReceptionReleaseResource,
                            ReceptionAllow,
                            ReceptionUnallow,
                            ReceptionReleaseResourceAll,
                            ReceptionCheckAccess,
                            ReceptionReleaseAccess,
                            ReceptionRecordAccess,
                            ReceptionReservation,
                        },
                        reception_result::{
                            ReceptionRegisterResult,
                            ReceptionUnregisterResult,
                            ReceptionUpdatePasswordResult,
                            ReceptionOwnResult,
                            ReceptionReleaseResourceResult,
                            ReceptionWhitelistAllowResult,
                            ReceptionBlacklistAllowResult,
                            ReceptionWhitelistUnallowResult,
                            ReceptionBlacklistUnallowResult,
                            ReceptionReleaseResourceAllResult,
                            ReceptionCheckAccessResult,
                            ReceptionReleaseAccessResult,
                            ReceptionRecordAccessResult,
                            ReceptionReservationResult,
                        },
                        host::{
                            Host,
                            host_input::{
                                HostCheckAccess,
                                HostRecordAccess,
                                HostReleaseAccess,
                                HostReservation,
                                HostUnreserve
                            },
                            host_result::{
                                HostCheckAccessResult,
                                HostRecordAccessResult,
                                HostReservationResult,
                                HostUnreserveResult,
                                HostReleaseAccessResult,
                            },
                            reservations::{
                                Reservations,
                                reservation_storage::{
                                    ReservationStorage
                                },
                                reservations_input::{
                                    ReservationsCheckAccess, 
                                    ReservationsReservation,
                                    ReservationsUnreserve
                                },
                                reservations_result::{
                                    ReservationsCheckAccessResult,
                                    ReservationsReserveResult,
                                    ReservationsUnreserveResult,
                                },
                            },
                            accesses::{
                                Accesses,
                                access_storage::{
                                    AccessStorage
                                },
                                accesses_result::{
                                    AccessesCheckAccessResult,
                                    AccessesRecordAccessResult,
                                    AccessesReleaseResult
                                },
                                accesses_input::{
                                    AccessesCheckAccess, 
                                    AccessesRecordAccess,
                                    AccessesRelease
                                }
                            }
                        },
                        owner::{
                            Owner,
                            owner_input::{
                                OwnerOwn,
                                OwnerRegister,
                                OwnerReleaseResource,
                                OwnerUpdatePassword,
                                OwnerUnregister,
                                OwnerAllow,
                                OwnerCheckAccess,
                                OwnerUnallow,
                                OwnerReleaseResourceAll,
                                OwnerAuthenticate
                            },
                            owner_result::{
                                OwnerOwnResult,
                                OwnerRegisterResult,
                                OwnerReleaseResourceResult,
                                OwnerUpdatePasswordResult,
                                OwnerUnregisterResult,
                                OwnerBlacklistAllowResult,
                                OwnerWhitelistAllowResult,
                                OwnerCheckAccessResult,
                                OwnerWhitelistUnallowResult,
                                OwnerBlacklistUnallowResult,
                                OwnerReleaseResourceAllResult,
                                OwnerAuthenticationResult
                            },
                            authenticator::{
                                Authenticator,
                                authenticator_input::{
                                    Authentication,
                                    AuthenticateRegister,
                                    AuthenticateUpdatePassword,
                                    AuthenticateUnregister
                                },
                                authenticator_result::{
                                    AuthenticationResult,
                                    AuthenticateRegistrationResult,
                                    AuthenticateUpdatePasswordResult,
                                    AuthenticateUnregisterResult
                                },
                                credential_storage::{
                                    CredentialStorage
                                },
                            },
                            controller::{
                                Controller,
                                controller_input::{
                                    ControllerOwn,
                                    ControllerReleaseResource,
                                    ControllerAllow,
                                    ControllerCheckAccess,
                                    ControllerReleaseId,
                                    ControllerCheckOwner,
                                    ControllerUnallow,
                                },
                                controller_result::{
                                    ControllerOwnResult,
                                    ControllerReleaseResourceResult,
                                    ControllerBlacklistAllowResult,
                                    ControllerWhitelistAllowResult,
                                    ControllerCheckAccessResult,
                                    ControllerReleaseIdResult,
                                    ControllerCheckOwnerResult,
                                    ControllerBlacklistUnallowResult,
                                    ControllerWhitelistUnallowResult
                                },
                                access_control::{
                                    AccessControl,
                                    access_control_input::{
                                        AccessControlCheckAccess,
                                        AccessControlAllow,
                                        AccessControlRelease,
                                        AccessControlUnallow
                                    },
                                    access_control_result::{
                                        AccessControlCheckAccessResult,
                                        AccessControlBlacklistAllowResult,
                                        AccessControlWhitelistAllowResult,
                                        AccessControlReleaseResult,
                                        AccessControlBlacklistUnallowResult,
                                        AccessControlWhitelistUnallowResult,
                                        AccessControlReleaseAllResult,
                                    },
                                    blacklist::{
                                        Blacklist,
                                        blacklist_input::{
                                            BlacklistCheckAccess,
                                            BlacklistAllow,
                                            BlacklistRelease,
                                            BlacklistUnallow
                                        },
                                        blacklist_result::{
                                            BlacklistCheckAccessResult,
                                            BlacklistAllowResult,
                                            BlacklistReleaseResult,
                                            BlacklistUnallowResult,
                                            BlacklistReleaseAllResult
                                        },
                                        blacklist_storage::{
                                            BlacklistStorage
                                        }
                                    },
                                    whitelist::{
                                        Whitelist,
                                        whitelist_input::{
                                            WhitelistCheckAccess,
                                            WhitelistAllow,
                                            WhitelistRelease,
                                            WhitelistUnallow
                                        },
                                        whitelist_result::{
                                            WhitelistCheckAccessResult,
                                            WhitelistAllowResult,
                                            WhitelistReleaseResult,
                                            WhitelistUnallowResult,
                                            WhitelistReleaseAllResult
                                        },
                                        whitelist_storage::{
                                            WhitelistStorage
                                        }
                                    }
                                },
                                resource_control::{
                                    ResourceControl,
                                    control_storage::{
                                        ControlStorage
                                    },
                                    resource_control_input::{
                                        ResourceControlCheckOwner,
                                        ResourceControlRelease,
                                        ResourceControlOwn,
                                        ResourceControlReleaseId
                                    },
                                    resource_control_result::{
                                        ResourceControlCheckOwnerResult,
                                        ResourceControlReleaseResult,
                                        ResourceControlOwnResult,
                                        ResourceControlReleaseIdResult,
                                        ResourceControlCheckOwnersResult
                                    }
                                }
                            }
                        }
                    }
                },
                automated_registry::{
                    AutomatedRegistry,
                    manual_registry::{
                        ManualRegistry,
                        stable_address::{
                            StableAddress
                        },
                        manual_registry_input::{
                            ManualRegistryAccessInput, 
                            ManualRegistryReplacementInput
                        },
                        manual_registry_result::{
                            ManualRegistryAccessResult, 
                            ManualRegistryReplacementResult
                        },
                        registry_storage::{
                            RegistryStorage
                        },
                    }
                }
            }
        },
        accessor::{
            Accessor
        }
    };
}