pub mod registry;
pub mod accessor;


pub mod prelude {
    pub const FUNCTION_LEVEL: tracing::Level = tracing::Level::DEBUG;
    pub use super::{
        registry::{
            Registry,
            singular_registry::{
                SingularRegistry,
                singular_registry_input::{
                    SingularRegistryAccessInput
                },
                singular_registry_result::{
                    SingularRegistryAccessResult
                },
                reception::{
                    CoordinatedReception,
                    coordinated_reception_input::{
                        ReceptionAccessPermissionInput,
                        ReceptionRecordAccessInput
                    },
                    coordinated_reception_result::{
                        ReceptionAccessPermission,
                    },
                    reception::{
                        Reception,
                        host::{
                            Host,
                            host_input::{
                                HostAccessPermissionInput
                            },
                            host_result::{
                                HostAccessPermissionResult
                            },
                            reservations::{
                                Reservations,
                                reservation_storage::{
                                    ReservationStorage
                                },
                                reservations_input::{
                                    ReservationsAccessPermissionInput, 
                                    ReserveInput,
                                    UnreserveInput
                                },
                                reservations_result::{
                                    ReservationsAccessPermissionResult,
                                    ReservationsReserveResult,
                                    ReservationsUnreserveResult
                                },
                            },
                            accesses::{
                                Accesses,
                                access_storage::{
                                    AccessStorage
                                },
                                accesses_result::{
                                    AccessPermission,
                                    RecordAccessResult,
                                    RemoveAccessResult
                                },
                                accesses_input::{
                                    PermitsAccessInput, 
                                    RecordAccessInput,
                                    RemoveAccessInput
                                }
                            }
                        },
                        owner::{
                            Owner,
                            authenticator::{
                                Authenticator
                            },
                            password_manager::{
                                PasswordManager
                            }
                        }
                    }
                },
                automated_registry::{
                    AutomatedRegistry,
                    manual_registry::{
                        ManualRegistry,
                        manual_registry_input::{
                            ManualRegistryAccessInput, 
                            ManualRegistryReplacementInput
                        },
                        manual_registry_result::{
                            ManualRegistryAccessResult, 
                            ManualRegistryReplacementResult
                        },
                        registry_storage::{
                            RegistryStorage
                        }
                    }
                }
            }
        },
        accessor::{
            Accessor
        }
    };
}